/* EETT SECTOR CONFS

  EETTCTA;CF1C;EETTALL
  EETTCTA;CF2;EETTE
  EETTCTA;CF2;EETTWF
  EETTCTA;CF2A;EETTEC
  EETTCTA;CF2A;EETTWF
  EETTCTA;CF3A;EETTEL
  EETTCTA;CF3A;EETTU
  EETTCTA;CF3A;EETTWLF
  EETTCTA;CF3B;EETTEL
  EETTCTA;CF3B;EETTEU
  EETTCTA;CF3B;EETTWF
  EETTCTA;CF5;EETTEL
  EETTCTA;CF5;EETTEU
  EETTCTA;CF5;EETTFED
  EETTCTA;CF5;EETTWL
  EETTCTA;CF5;EETTWU
  EETTCTA;CONF1;EETTALL

  EFIN SECTOR CONFS

  EFINCTA;CONF1;EFINALL
  EFINCTA;CONF2;EFIN10EN
  EFINCTA;CONF2;EFIN4ABCD
  EFINCTA;CONF2A;EFIN6AF
  EFINCTA;CONF2A;EFIN8GN
  EFINCTA;CONF2B;EFIN7AG
  EFINCTA;CONF2B;EFIN7VN
  EFINCTA;CONF2C;EFIN5HJLNV
  EFINCTA;CONF2C;EFIN9AGKM
  EFINCTA;CONF2D;EFIN10AJ
  EFINCTA;CONF2D;EFIN4KLMN
  EFINCTA;CONF2E;EFIN6ADLN
  EFINCTA;CONF2E;EFIN8EM
  EFINCTA;CONF2F;EFIN6EJ
  EFINCTA;CONF2F;EFIN8ADKN
  EFINCTA;CONF2G;EFIN10AFKN
  EFINCTA;CONF2G;EFIN4GVHJ
  EFINCTA;CONF2H;EFIN10ACHN
  EFINCTA;CONF2H;EFIN4DEFG
  EFINCTA;CONF2I;EFIN11XDEF
  EFINCTA;CONF2I;EFIN3DEF
  EFINCTA;CONF2J;EFIN10AGKM
  EFINCTA;CONF2J;EFIN4HJNV
  EFINCTA;CONF2K;EFIN12XHJ
  EFINCTA;CONF2K;EFIN2HJ
  EFINCTA;CONF2L;EFIN11XHJV
  EFINCTA;CONF2L;EFIN3VHJ
  EFINCTA;CONF3;EFIN2EF
  EFINCTA;CONF3;EFIN4ABCD
  EFINCTA;CONF3;EFIN8GN
  EFINCTA;CONF3A;EFIN3EFG
  EFINCTA;CONF3A;EFIN4ABCD
  EFINCTA;CONF3A;EFIN7VN
  EFINCTA;CONF3B;EFIN3ABC
  EFINCTA;CONF3B;EFIN3DEF
  EFINCTA;CONF3B;EFIN8GN
  EFINCTA;CONF3C;EFIN3ABC
  EFINCTA;CONF3C;EFIN4DEFG
  EFINCTA;CONF3C;EFIN7VN
  EFINCTA;CONF3D;EFIN4ABCD
  EFINCTA;CONF3D;EFIN4KLMN
  EFINCTA;CONF3D;EFIN6EJ
  EFINCTA;CONF3E;EFIN4GVHJ
  EFINCTA;CONF3E;EFIN4KLMN
  EFINCTA;CONF3E;EFIN6AF
  EFINCTA;CONF3F;EFIN3VHJ
  EFINCTA;CONF3F;EFIN4KLMN
  EFINCTA;CONF3F;EFIN7AG
  EFINCTA;CONF3G;EFIN2HJ
  EFINCTA;CONF3G;EFIN4KLMN
  EFINCTA;CONF3G;EFIN8AV
  EFINCTA;CONF3H;EFIN2LN
  EFINCTA;CONF3H;EFIN4ABCD
  EFINCTA;CONF3H;EFIN8EM
  EFINCTA;CONF3I;EFIN2LN
  EFINCTA;CONF3I;EFIN6AF
  EFINCTA;CONF3I;EFIN6GM
  EFINCTA;CONF3J;EFIN2LN
  EFINCTA;CONF3J;EFIN5VHJKM
  EFINCTA;CONF3J;EFIN7AG
  EFINCTA;CONF3K;EFIN3VHJ
  EFINCTA;CONF3K;EFIN4ABCD
  EFINCTA;CONF3K;EFIN7MID
  EFINCTA;CONF3L;EFIN3VHJ
  EFINCTA;CONF3L;EFIN5GKLMN
  EFINCTA;CONF3L;EFIN6AF
  EFINCTA;CONF3M;EFIN2HJ
  EFINCTA;CONF3M;EFIN4ABCD
  EFINCTA;CONF3M;EFIN8EGVN
  EFINCTA;CONF3N;EFIN2HJ
  EFINCTA;CONF3N;EFIN6AF
  EFINCTA;CONF3N;EFIN6GVKN
  EFINCTA;CONF3O;EFIN2HJ
  EFINCTA;CONF3O;EFIN5KLMNV
  EFINCTA;CONF3O;EFIN7AG
  EFINCTA;CONF4;EFIN2EF
  EFINCTA;CONF4;EFIN4ABCD
  EFINCTA;CONF4;EFIN4GVHJ
  EFINCTA;CONF4;EFIN4KLMN
  EFINCTA;CONF4A;EFIN2EF
  EFINCTA;CONF4A;EFIN3VHJ
  EFINCTA;CONF4A;EFIN4ABCD
  EFINCTA;CONF4A;EFIN5GKLMN
  EFINCTA;CONF4B;EFIN2EF
  EFINCTA;CONF4B;EFIN2HJ
  EFINCTA;CONF4B;EFIN4ABCD
  EFINCTA;CONF4B;EFIN6GVKN
  EFINCTA;CONF4C;EFIN2EF
  EFINCTA;CONF4C;EFIN2LN
  EFINCTA;CONF4C;EFIN4ABCD
  EFINCTA;CONF4C;EFIN6GM
  EFINCTA;CONF4D;EFIN3EFG
  EFINCTA;CONF4D;EFIN3VHJ
  EFINCTA;CONF4D;EFIN4ABCD
  EFINCTA;CONF4D;EFIN4KLMN
  EFINCTA;CONF4E;EFIN2LN
  EFINCTA;CONF4E;EFIN3EFG
  EFINCTA;CONF4E;EFIN4ABCD
  EFINCTA;CONF4E;EFIN5VHJKM
  EFINCTA;CONF4F;EFIN2HJ
  EFINCTA;CONF4F;EFIN3EFG
  EFINCTA;CONF4F;EFIN4ABCD
  EFINCTA;CONF4F;EFIN5KLMNV
  EFINCTA;CONF4G;EFIN2HJ
  EFINCTA;CONF4G;EFIN4ABCD
  EFINCTA;CONF4G;EFIN4EFGV
  EFINCTA;CONF4G;EFIN4KLMN
  EFINCTA;CONF4H;EFIN3ABC
  EFINCTA;CONF4H;EFIN3DEF
  EFINCTA;CONF4H;EFIN4GVHJ
  EFINCTA;CONF4H;EFIN4KLMN
  EFINCTA;CONF4I;EFIN3ABC
  EFINCTA;CONF4I;EFIN3DEF
  EFINCTA;CONF4I;EFIN3VHJ
  EFINCTA;CONF4I;EFIN5GKLMN
  EFINCTA;CONF4J;EFIN2LN
  EFINCTA;CONF4J;EFIN3GKM
  EFINCTA;CONF4J;EFIN3VHJ
  EFINCTA;CONF4J;EFIN6AF
  EFINCTA;CONF4K;EFIN2HJ
  EFINCTA;CONF4K;EFIN2LN
  EFINCTA;CONF4K;EFIN3VKM
  EFINCTA;CONF4K;EFIN7AG
  EFINCTA;CONF5;EFIN2EF
  EFINCTA;CONF5;EFIN2KM
  EFINCTA;CONF5;EFIN2LN
  EFINCTA;CONF5;EFIN4ABCD
  EFINCTA;CONF5;EFIN4GVHJ
  EFINCTA;CONF5A;EFIN2KM
  EFINCTA;CONF5A;EFIN2LN
  EFINCTA;CONF5A;EFIN3EFG
  EFINCTA;CONF5A;EFIN3VHJ
  EFINCTA;CONF5A;EFIN4ABCD
  EFINCTA;CONF5B;EFIN2HJ
  EFINCTA;CONF5B;EFIN2KM
  EFINCTA;CONF5B;EFIN2LN
  EFINCTA;CONF5B;EFIN4ABCD
  EFINCTA;CONF5B;EFIN4EFGV
  EFINCTA;CONF5C;EFIN2HJ
  EFINCTA;CONF5C;EFIN2LN
  EFINCTA;CONF5C;EFIN3EFG
  EFINCTA;CONF5C;EFIN3VKM
  EFINCTA;CONF5C;EFIN4ABCD
  EFINCTA;CONF5D;EFIN2EF
  EFINCTA;CONF5D;EFIN2GV
  EFINCTA;CONF5D;EFIN2HJ
  EFINCTA;CONF5D;EFIN4ABCD
  EFINCTA;CONF5D;EFIN4KLMN
  EFINCTA;CONF5E;EFIN2EF
  EFINCTA;CONF5E;EFIN2HJ
  EFINCTA;CONF5E;EFIN2LN
  EFINCTA;CONF5E;EFIN4ABCD
  EFINCTA;CONF5E;EFIN4GVKM
  EFINCTA;CONF5F;EFIN2FG
  EFINCTA;CONF5F;EFIN3VHJ
  EFINCTA;CONF5F;EFIN4ABCD
  EFINCTA;CONF5F;EFIN4KLMN
  EFINCTA;CONF5F;EFINE
  EFINCTA;CONF5G;EFIN2GV
  EFINCTA;CONF5G;EFIN2HJ
  EFINCTA;CONF5G;EFIN3ABC
  EFINCTA;CONF5G;EFIN3DEF
  EFINCTA;CONF5G;EFIN4KLMN
*/

const sectorConfs = (country, confName) => {
  if (country === 'EE') {
    switch (confName) {
      case 'CONF1' : return [
        ['eette', 'eettw']
      ]
      case 'CF3A':
      case 'CF3B':
      case 'CF2': return [
        ['eettw', 'eettfed'],
        ['eette']
      ]
      case 'CF2A': return [
        ['eettw', 'eette'],
        ['eettfed']
      ]
      case 'CF5': return [
        ['eettw'],
        ['eette'],
        ['eettfed']
      ]
    }
  }
  if (country === 'EF') {
    switch (confName) {
      case 'CONF1': return [
        ['efina', 'efinb', 'efinc', 'efind', 'efine', 'efinf', 'efing', 'efinh', 'efinj', 'efink', 'efinl', 'efinm', 'efinn', 'efinv']
      ]
      case 'CONF2': return [
        ['efina', 'efinb', 'efinc', 'efind'],
        ['efine', 'efinf', 'efing', 'efinh', 'efinj', 'efink', 'efinl', 'efinm', 'efinn', 'efinv']
      ]
      case 'CONF2A': return [
        ['efina', 'efinb', 'efinc', 'efind', 'efine', 'efinf'],
        ['efing', 'efinh', 'efinj', 'efink', 'efinl', 'efinm', 'efinn', 'efinv']
      ]
      case 'CONF2B': return [
        ['efina', 'efinb', 'efinc', 'efind', 'efine', 'efinf', 'efing'],
        ['efinh', 'efinj', 'efink', 'efinl', 'efinm', 'efinn', 'efinv']
      ]
    }
  }
  return []
}

export default { sectorConfs }

